=== maguishuita/projet_IFALL/xml/films.dtd
<!ELEMENT cinema (film+)>
<!ELEMENT film (titre, genre, duree, realisateur, langue, acteurs, annee, notes?, horaires)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT duree (#PCDATA)>
<!ELEMENT realisateur (#PCDATA)>
<!ELEMENT langue (#PCDATA)>
<!ELEMENT acteurs (acteur+)>
<!ELEMENT acteur (#PCDATA)>
<!ELEMENT annee (#PCDATA)>
<!ELEMENT notes (presse?, spectateurs?)>
<!ELEMENT presse (#PCDATA)>
<!ELEMENT spectateurs (#PCDATA)>
<!ELEMENT synopsis (#PCDATA)>
<!ELEMENT horaires (horaire+)>
<!ELEMENT horaire (#PCDATA)>

=== maguishuita/projet_IFALL/xml/films.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cinema SYSTEM "films.dtd">
<cinema>
  
  <!-- Ajouter plus de films ici -->
<film><titre>deguene</titre><genre>fa</genre><duree>4</duree><realisateur>faty</realisateur><langue>francais</langue><annee>2029</annee><synopsis>se</synopsis><acteurs><acteur>qw</acteur><acteur>er</acteur><acteur>ty</acteur></acteurs></film><film><titre>maman</titre><genre>die</genre><duree>5ans</duree><realisateur>astou</realisateur><langue>anglais</langue><annee>2024</annee><synopsis>recit</synopsis><acteurs><acteur>deguene</acteur><acteur>mane</acteur></acteurs></film><film><titre>yaya</titre><genre>m</genre><duree>165min</duree><realisateur>takkino</realisateur><langue>anglais</langue><annee>2023</annee><synopsis>qwertyu</synopsis><acteurs><acteur>var</acteur><acteur>war</acteur><acteur>yaya</acteur></acteurs></film></cinema>
